/*
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Sequence.java
 * Copyright (C) 2024
 */

package weka.associations.spade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a sequence (ordered list of elements/itemsets) in the
 * SPADE algorithm. Each sequence has an associated IdList for
 * support counting.
 *
 * A sequence is represented as: &lt;{a,b}, {c}, {d,e}&gt;
 * meaning item a and b occur together, then c, then d and e together.
 *
 * @author Weka SPADE Implementation
 */
public class Sequence implements Serializable {

  /** for serialization */
  private static final long serialVersionUID = 3L;

  /** The ordered list of elements (itemsets) in this sequence */
  private List<Element> m_Elements;

  /** The ID-List associated with this sequence */
  private IdList m_IdList;

  /** The support count (number of distinct sequences containing this pattern) */
  private int m_Support;

  /**
   * Constructor. Creates an empty sequence.
   */
  public Sequence() {
    m_Elements = new ArrayList<Element>();
    m_IdList = new IdList();
    m_Support = 0;
  }

  /**
   * Constructor. Creates a sequence with a single element containing one item.
   *
   * @param item the single item
   */
  public Sequence(String item) {
    m_Elements = new ArrayList<Element>();
    m_Elements.add(new Element(item));
    m_IdList = new IdList();
    m_Support = 0;
  }

  /**
   * Constructor. Creates a sequence from a list of elements.
   *
   * @param elements the list of elements
   */
  public Sequence(List<Element> elements) {
    m_Elements = new ArrayList<Element>(elements);
    m_IdList = new IdList();
    m_Support = 0;
  }

  /**
   * Adds an element to the end of this sequence.
   *
   * @param element the element to add
   */
  public void addElement(Element element) {
    m_Elements.add(element);
  }

  /**
   * Returns the list of elements in this sequence.
   *
   * @return the elements
   */
  public List<Element> getElements() {
    return m_Elements;
  }

  /**
   * Returns the element at the given index.
   *
   * @param index the index
   * @return the element
   */
  public Element getElement(int index) {
    return m_Elements.get(index);
  }

  /**
   * Returns the number of elements in this sequence.
   *
   * @return the length
   */
  public int length() {
    return m_Elements.size();
  }

  /**
   * Returns the total number of items across all elements.
   * This is the "k" in "k-sequence".
   *
   * @return the total item count
   */
  public int itemCount() {
    int count = 0;
    for (Element e : m_Elements) {
      count += e.size();
    }
    return count;
  }

  /**
   * Returns the ID-List associated with this sequence.
   *
   * @return the ID-List
   */
  public IdList getIdList() {
    return m_IdList;
  }

  /**
   * Sets the ID-List for this sequence.
   *
   * @param idList the ID-List to set
   */
  public void setIdList(IdList idList) {
    m_IdList = idList;
    m_Support = idList.getSupport();
  }

  /**
   * Returns the support of this sequence.
   *
   * @return the support count
   */
  public int getSupport() {
    return m_Support;
  }

  /**
   * Sets the support of this sequence.
   *
   * @param support the support count
   */
  public void setSupport(int support) {
    m_Support = support;
  }

  /**
   * Returns the last element of this sequence.
   *
   * @return the last element, or null if empty
   */
  public Element getLastElement() {
    if (m_Elements.isEmpty()) return null;
    return m_Elements.get(m_Elements.size() - 1);
  }

  /**
   * Returns the last item of the last element (used for atom identification
   * when building equivalence classes).
   *
   * @return the last item, or null if empty
   */
  public String getLastItem() {
    Element lastElem = getLastElement();
    if (lastElem == null || lastElem.size() == 0) return null;
    return lastElem.getItem(lastElem.size() - 1);
  }

  /**
   * Determines if this atom was generated by a sequence extension (the last
   * item is in its own element) vs an itemset extension (the last item was
   * added to the last element of the prefix).
   *
   * For atom identification in equivalence classes:
   * - Sequence extension: last element has 1 item
   * - Itemset extension: last element has >1 items
   *
   * @return true if this is a sequence extension atom
   */
  public boolean isSequenceExtension() {
    if (m_Elements.isEmpty()) return false;
    return m_Elements.get(m_Elements.size() - 1).size() == 1 && m_Elements.size() > 1;
  }

  /**
   * Creates a copy of this sequence.
   *
   * @return a new Sequence with copied elements
   */
  public Sequence copy() {
    List<Element> copiedElements = new ArrayList<Element>();
    for (Element e : m_Elements) {
      copiedElements.add(e.copy());
    }
    Sequence result = new Sequence(copiedElements);
    result.m_Support = this.m_Support;
    // Note: IdList is not deep-copied for performance
    result.m_IdList = this.m_IdList;
    return result;
  }

  /**
   * Creates a new sequence by extending this sequence with a sequence
   * extension (adding item as a new element at the end).
   *
   * @param item the item to add as a new element
   * @return the extended sequence
   */
  public Sequence sequenceExtend(String item) {
    Sequence result = this.copy();
    result.addElement(new Element(item));
    return result;
  }

  /**
   * Creates a new sequence by extending this sequence with an itemset
   * extension (adding item to the last element).
   *
   * @param item the item to add to the last element
   * @return the extended sequence
   */
  public Sequence itemsetExtend(String item) {
    Sequence result = this.copy();
    result.getLastElement().addItem(item);
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) return true;
    if (!(obj instanceof Sequence)) return false;
    Sequence other = (Sequence) obj;
    return m_Elements.equals(other.m_Elements);
  }

  @Override
  public int hashCode() {
    return m_Elements.hashCode();
  }

  /**
   * Returns a string representation of this sequence.
   * Format: &lt;{a,b}, {c}, {d}&gt;
   *
   * @return the string representation
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("<");
    for (int i = 0; i < m_Elements.size(); i++) {
      if (i > 0) sb.append(", ");
      Element e = m_Elements.get(i);
      sb.append("{");
      for (int j = 0; j < e.size(); j++) {
        if (j > 0) sb.append(", ");
        sb.append(e.getItem(j));
      }
      sb.append("}");
    }
    sb.append(">");
    return sb.toString();
  }

  /**
   * Returns a formatted string with support information.
   *
   * @param totalSequences the total number of sequences for percentage
   * @return formatted string
   */
  public String toStringWithSupport(int totalSequences) {
    double supportPct = (totalSequences > 0) ?
        (double) m_Support / totalSequences * 100.0 : 0;
    return String.format("  %s   (support: %d, %.1f%%)",
        toString(), m_Support, supportPct);
  }
}
